### ISSUE TITLE
Library isn't compatible with Java 7

### ISSUE THREAD

**Issue by akkie** [chanan/AkkaGuice#2]
Hi,

It seems that the library is compiled with Java 8 because I get the following error:

```
play.api.UnexpectedException: Unexpected exception[UnsupportedClassVersionError: akkaGuice/AkkaGuiceModule : Unsupported major.minor version 52.0]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:170) ~[play_2.11-2.3.4.jar:2.3.4]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.4.jar:2.3.4]
    at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.4.jar:2.3.4]
    at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.4.jar:2.3.4]
Caused by: java.lang.UnsupportedClassVersionError: akkaGuice/AkkaGuiceModule : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_51]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_51]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_51]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_51]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_51]
```

Would it be possible to compile the library with Java 7 backward compatibility.

**Comment by akkie** [comment]
Ah, I see that you use the new Lambda syntax from Java 8. So backward compatibility isn't given.

**Comment by akkie** [comment]
But only for the sample. This lib itself is backward compatible.

**Comment by chanan** [comment]
I am not 100% sure how to do this. I never noticed before that Java does not have conditional compilation. Any thoughts on this?

**Comment by akkie** [comment]
I haven't done this before. But it seems that you must add `javacOptions ++= Seq("-source", "1.8", "-target", "1.7")` to you `build.sbt` file.

http://stackoverflow.com/questions/15492948/javac-source-and-target-options
http://www.scala-sbt.org/0.12.3/docs/Detailed-Topics/Java-Sources.html

**Comment by chanan** [comment]
I will try this out, but if it doesn't work I will simply remove the class. I can always add another repo for a Java 8 sample project. The only reason it is there in the first place is to check that AkkaGuice works correctly with AbstractActor. Either way, I should have something posted in a day or two.

**Comment by akkie** [comment]
I think you must not remove the file, because you can publish the module individually. As long as the "sbt publish" command will be executed in the module directory on a 1.7 JVM, all should be OK.

**Comment by chanan** [comment]
Ah, I thought you wanted the sample app to compile in Java 7 as well. Ok, I will add the line to build.sbt and commit a new version. Let me know if it works.

**Comment by chanan** [comment]
Try using AkkaGuice 0.8.1 it is compiled with 1.7 java switch.

**Comment by akkie** [comment]
It works! Thanks!

**Comment by akkie** [comment]
I've the same issue with version 0.8.3. It seems that the compiler setting was removed with https://github.com/chanan/AkkaGuice/commit/ecf3c8e46109aed6e318c3be169a0befe826088c
