### ISSUE TITLE
PerRequest Actor getting the same name

### ISSUE THREAD

**Issue by chanan** [chanan/AkkaGuice#4]
Error in custom provider, akka.actor.InvalidActorNameException: actor name [PerRequest-114326323442451120] is not unique!
  at akkaGuice.AkkaGuiceModule.RegisterActors(AkkaGuiceModule.java:59)
  while locating akka.actor.ActorRef annotated with @com.google.inject.name.Named(value=PerRequest)
    for parameter 4 at controllers.Application.<init>(Application.java:24)
  while locating controllers.Application

**Comment by chanan** [comment]
This happens when trying to inject into the constructor a per request actor. Singleton actors are fine and also using PropsContext is.
